# Module 20: Circle (databse)
Chandler Kaiden, crkaide

In [1]:
# Dependencies

import pandas as pd

In [2]:
# Read data in from github

url = "https://raw.githubusercontent.com/ddw26/Team-Vand/main/catch_20201.csv"
data = pd.read_csv(url)
data.head(5)

,common,strat_id,psu_id,YEAR,ST,MODE_FX,AREA_X,ID_CODE,SUB_REG,WAVE,...,fl_reg,wp_catch,tot_cat,wgt_ab1,tot_len,landing,var_id,arx_method,alt_flag,date_published
0,COMMON SNOOK,2020011253weS:8AM-8PM,2.020110e+21,2020,12,3,1,1.534720e+15,6,1,...,8,37775.61978,1.0,0.0,0.0,0.0,2020011253weS:8AM-8PM,NaN,0,5/4/21
1,SERGEANT MAJOR,2020011253weS:8AM-8PM,2.020110e+21,2020,12,3,1,1.534720e+15,6,1,...,8,37775.61978,2.0,0.0,0.0,0.0,2020011253weS:8AM-8PM,NaN,0,5/4/21
2,SEA BASS FAMILY,2020011253weS:8AM-8PM,2.020110e+21,2020,12,3,1,1.534720e+15,6,1,...,8,37775.61978,1.0,0.0,0.0,0.0,2020011253weS:8AM-8PM,NaN,0,5/4/21
3,GRUNT FAMILY,2020011253weS:8AM-8PM,2.020110e+21,2020,12,3,1,1.534720e+15,6,1,...,8,37775.61978,1.0,0.0,0.0,0.0,2020011253weS:8AM-8PM,NaN,0,5/4/21
4,UNIDENTIFIED FISH,2020011253weS:8AM-8PM,2.020110e+21,2020,12,3,1,1.534720e+15,6,1,...,8,37775.61978,5.0,0.0,0.0,0.0,2020011253weS:8AM-8PM,NaN,0,5/4/21

### Identify columns to retain/drop
#### (based on group discussion; larger file available so replacing what we uploaded to github with the file that contains all variables instead of approx. 50% of the below)

Columns to keep:

ADD_HRS
AREA_X
ART_REEF
BOAT_HRS
CATCH
DIST
DISTKEYS
FSHINSP_A
GEAR
HRS_DTD
HRSF
KOD
MODE_F
MODE_FX
MODE2001
MONTH
PRIM1
PRIM2
REGION
RIG
SUB_REG
TIME
TSN1
WAVE

Columns to drop:

ADD_PH
AGE
AREA
AREA_NC
ASG_CODE
CELLTYPE
CNTRBTRS
CNTY
CNTY_RES
COASTAL
COMPFLAG
COUNTY
DATE1
F_BY_P
FFDAYS12
FFDAYS2
FIRST
GENDER
ID_CODE
INTSITE
LEADER
LICENSE
MODE_ASG
MONITOR
MUNI_RES
MUNI_TRP
NEW_LIST
NUM_FISH_A
NUM_TYP2
NUM_TYP3
NUM_TYP4
NUM_TYP6
NUM_TYP9
ON_LIST
PARTY
PRIM1_COMMON
PRIM2_COMMON
PRT_CODE
PSU_ID
PVT_RES
REEFCODE
REG_RES
SEP_FISH
ST
ST_RES
STRAT_ID
STRAT_INTERVAL
TELEFON
TOURN
TSN2
TURTLE
WP_INT
YEAR
ZIP

In [4]:
data.columns

Index(['common', 'strat_id', 'psu_id', 'YEAR', 'ST', 'MODE_FX', 'AREA_X',
       'ID_CODE', 'SUB_REG', 'WAVE', 'kod', 'SP_CODE', 'CLAIM', 'RELEASE',
       'HARVEST', 'CLAIM_UNADJ', 'HARVEST_UNADJ', 'RELEASE_UNADJ', 'tot_len_a',
       'wgt_a', 'tot_len_b1', 'wgt_b1', 'region', 'month', 'wp_int', 'fl_reg',
       'wp_catch', 'tot_cat', 'wgt_ab1', 'tot_len', 'landing', 'var_id',
       'arx_method', 'alt_flag', 'date_published'],
      dtype='object')